import Card from "../components/Card2";

function Economy() {
  return (
    <section className="economy">
      <h2>Economic Impact</h2>

      <table>
        <thead>
          <tr>
            <th>Stakeholders</th>
            <th>Positive Impact</th>
            <th>Negative Impact</th>
            <th>Fact/Evidence</th>
            <th>Source</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>Players</td>

            <td>
              More realistic and engaging gameplay may improve player
              satisfaction and increase the value of games.
            </td>

            <td>
              AI-driven features may increase game prices or require
              more powerful hardware.
            </td>

            <td>
              Complex NPC systems can create more immersive experiences,
              but may demand additional computing resources from users.
            </td>

            <td>
              International Energy Agency (IEA), Energy and AI
            </td>
          </tr>

          <tr>
            <td>Game Developers</td>

            <td>
              NPC behavior AI can reduce repetitive work and improve
              development efficiency.
            </td>

            <td>
              Developing, testing, and maintaining advanced AI systems
              can increase production costs.
            </td>

            <td>
              Developers may save time on routine NPC behaviors, but
              investment in AI technology and skilled workers can be
              expensive.
            </td>

            <td>
              OECD; IGDA
            </td>
          </tr>

          <tr>
            <td>Game Industry</td>

            <td>
              AI may create new jobs and support innovation within the
              gaming industry.
            </td>

            <td>
              Some traditional development roles may be reduced or
              transformed by automation.
            </td>

            <td>
              AI tools can automate parts of development while creating
              demand for AI specialists and technical experts.
            </td>

            <td>
              World Economic Forum; OECD
            </td>
          </tr>

          <tr>
            <td>Society</td>

            <td>
              Growth of the gaming industry can contribute to economic
              activity and technological advancement.
            </td>

            <td>
              Unequal access to advanced technology may increase economic
              disparities.
            </td>

            <td>
              The benefits of AI are often concentrated among companies
              with greater financial and technical resources.
            </td>

            <td>
              OECD
            </td>
          </tr>
        </tbody>
      </table>
      <p>*Generated by AI</p>
    </section>
  );
}

export default Economy;